// wexler-notes-next/src/components/reading/ReadingEnhancer.tsx
// src/components/reading/ReadingEnhancer.tsx
'use client'

import { useReadingProgress } from '@/hooks/useReadingProgress'
import { usePathname } from 'next/navigation'
import { useCallback, useEffect, useRef, useState } from 'react'
import styles from './ReadingEnhancer.module.css'

interface Heading {
  id: string
  level: 'h2' | 'h3'
  text: string
}

const POSITION_KEY = 'wexler.chapterSpotlight.position'
const COLLAPSE_KEY = 'wexler.chapterSpotlight.collapsed'

function clamp(v: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, v))
}

function shorten(text: string): string {
  const value = (text || '').replace(/\s+/g, ' ').trim()
  if (value.length <= 24) return value
  return `${value.slice(0, 24)}...`
}

export default function ReadingEnhancer() {
  const pathname = usePathname()
  const { progress, showBackToTop, scrollToTop } = useReadingProgress()
  const [headings, setHeadings] = useState<Heading[]>([])
  const [activeId, setActiveId] = useState('')
  const [isCollapsed, setIsCollapsed] = useState(false)
  const [position, setPosition] = useState<{ left: number; top: number } | null>(null)
  const [isDragging, setIsDragging] = useState(false)
  const [isWideScreen, setIsWideScreen] = useState(false)
  const panelRef = useRef<HTMLDivElement>(null)
  const rafRef = useRef(0)
  const latestPosRef = useRef<{ left: number; top: number } | null>(null)

  const showNav = isWideScreen && headings.length > 0

  useEffect(() => {
    latestPosRef.current = position
  }, [position])

  useEffect(() => {
    try {
      const rawPos = localStorage.getItem(POSITION_KEY)
      const rawCollapsed = localStorage.getItem(COLLAPSE_KEY)
      if (rawPos) {
        const parsed = JSON.parse(rawPos)
        if (
          typeof parsed?.left === 'number' &&
          Number.isFinite(parsed.left) &&
          typeof parsed?.top === 'number' &&
          Number.isFinite(parsed.top)
        ) {
          setPosition({ left: parsed.left, top: parsed.top })
        }
      }
      setIsCollapsed(rawCollapsed === '1')
    } catch {
      // ignore storage errors
    }
  }, [])

  useEffect(() => {
    const mq = window.matchMedia('(min-width: 1280px)')
    setIsWideScreen(mq.matches)
    const handler = (e: MediaQueryListEvent) => setIsWideScreen(e.matches)
    mq.addEventListener('change', handler)
    return () => mq.removeEventListener('change', handler)
  }, [])

  useEffect(() => {
    const collect = () => {
      const nodes = document.querySelectorAll('.docContent h2[id], .docContent h3[id]')
      const next = Array.from(nodes).map((node) => ({
        id: node.id,
        level: node.tagName.toLowerCase() as 'h2' | 'h3',
        text: shorten(node.textContent || ''),
      }))
      setHeadings(next)
      setActiveId(next[0]?.id ?? '')
    }
    const timer = window.setTimeout(collect, 60)
    return () => window.clearTimeout(timer)
  }, [pathname])

  useEffect(() => {
    if (!showNav || position !== null || !panelRef.current) return
    const rect = panelRef.current.getBoundingClientRect()
    const next = {
      left: clamp(rect.left, 10, window.innerWidth - 226),
      top: clamp(rect.top, 10, window.innerHeight - 320),
    }
    setPosition(next)
  }, [showNav, position])

  useEffect(() => {
    const handler = () => {
      if (rafRef.current) return
      rafRef.current = requestAnimationFrame(() => {
        rafRef.current = 0
        if (!headings.length) return
        const marker = window.scrollY + 140
        let current = headings[0]
        for (const heading of headings) {
          const node = document.getElementById(heading.id)
          if (node && node.offsetTop <= marker) current = heading
          else break
        }
        setActiveId(current.id)
      })
    }
    window.addEventListener('scroll', handler, { passive: true })
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current)
      window.removeEventListener('scroll', handler)
    }
  }, [headings])

  const onPointerDown = useCallback((e: React.PointerEvent) => {
    if ((e.target as HTMLElement).closest('button')) return
    if (!latestPosRef.current) return

    const startX = e.clientX
    const startY = e.clientY
    const startPos = latestPosRef.current

    const onMove = (ev: PointerEvent) => {
      const next = {
        left: clamp(startPos.left + (ev.clientX - startX), 10, window.innerWidth - 226),
        top: clamp(startPos.top + (ev.clientY - startY), 10, window.innerHeight - 320),
      }
      latestPosRef.current = next
      setPosition(next)
    }

    const onUp = () => {
      setIsDragging(false)
      window.removeEventListener('pointermove', onMove)
      window.removeEventListener('pointerup', onUp)
      const latest = latestPosRef.current
      if (!latest) return
      try {
        localStorage.setItem(POSITION_KEY, JSON.stringify(latest))
      } catch {
        // ignore storage errors
      }
    }

    setIsDragging(true)
    window.addEventListener('pointermove', onMove)
    window.addEventListener('pointerup', onUp)
  }, [])

  const toggleCollapse = () => {
    setIsCollapsed((prev) => {
      const next = !prev
      try {
        localStorage.setItem(COLLAPSE_KEY, next ? '1' : '0')
      } catch {
        // ignore storage errors
      }
      return next
    })
  }

  return (
    <>
      <div className={styles.progress} aria-hidden="true">
        <span className={styles.progressBar} style={{ transform: `scaleX(${progress})` }} />
      </div>

      {showBackToTop && (
        <button className={styles.backTop} onClick={() => scrollToTop()} aria-label="回到顶部">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" width="18" height="18">
            <path d="M12 19V5M5 12l7-7 7 7" />
          </svg>
        </button>
      )}

      {showNav && position !== null && (
        <aside
          ref={panelRef}
          className={`${styles.spotlight} ${isDragging ? styles.dragging : ''} ${isCollapsed ? styles.collapsed : ''}`}
          style={{ left: position.left, top: position.top }}
          aria-label="章节导航"
          onPointerDown={onPointerDown}
        >
          <div className={styles.dragHandle}>
            <p className={styles.spotlightTitle}>章节导航</p>
            <button
              type="button"
              className={`${styles.toggleBtn} ${isCollapsed ? styles.toggleCollapsed : ''}`}
              aria-label={isCollapsed ? '展开章节导航' : '收起章节导航'}
              onPointerDown={(e) => e.stopPropagation()}
              onClick={(e) => {
                e.stopPropagation()
                toggleCollapse()
              }}
            />
          </div>
          {!isCollapsed && (
            <div className={styles.spotlightBody}>
              {headings.map((heading) => (
                <a
                  key={heading.id}
                  href={`#${heading.id}`}
                  className={`${styles.navLink} ${heading.level === 'h3' ? styles.navLinkH3 : ''} ${heading.id === activeId ? styles.navLinkActive : ''}`}
                >
                  {heading.text}
                </a>
              ))}
            </div>
          )}
        </aside>
      )}
    </>
  )
}

// my-knowledge-base/docs/.vitepress/theme/components/ReadingEnhancer.vue
<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { useRoute } from 'vitepress'

const route = useRoute()
const STORAGE_KEY = 'wexler.chapterSpotlight.position'
const COLLAPSE_KEY = 'wexler.chapterSpotlight.collapsed'

const progress = ref(0)
const showBackToTop = ref(false)
const isBackToTopAnimating = ref(false)
const navItems = ref([])
const activeId = ref('')
const isDocPage = ref(false)
const isWideScreen = ref(false)
const chapterPanel = ref(null)
const chapterPosition = ref(null)
const isDragging = ref(false)
const isCollapsed = ref(false)

let dragOffsetX = 0
let dragOffsetY = 0

let headingNodes = []
let rafId = 0
let routeTimer = null

const showProgress = computed(() => isDocPage.value)
const showChapterNav = computed(
  () => isDocPage.value && isWideScreen.value && navItems.value.length > 0
)
const chapterStyle = computed(() => {
  if (!chapterPosition.value) return null
  return {
    left: `${chapterPosition.value.left}px`,
    top: `${chapterPosition.value.top}px`
  }
})

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value))
}

function scrollToTop(smooth = true) {
  if (isBackToTopAnimating.value) return
  isBackToTopAnimating.value = true
  window.scrollTo({ top: 0, behavior: smooth ? 'smooth' : 'instant' })
  setTimeout(() => {
    isBackToTopAnimating.value = false
  }, 600)
}

function shortText(value) {
  const text = (value || '').replace(/\s+/g, ' ').trim()
  if (text.length <= 24) return text
  return `${text.slice(0, 24)}...`
}

function saveChapterPosition() {
  if (!chapterPosition.value) return
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(chapterPosition.value))
  } catch (error) {
    // Ignore storage errors (private mode or quota).
  }
}

function loadChapterPosition() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (!raw) return
    const parsed = JSON.parse(raw)
    if (
      typeof parsed?.left === 'number' &&
      Number.isFinite(parsed.left) &&
      typeof parsed?.top === 'number' &&
      Number.isFinite(parsed.top)
    ) {
      chapterPosition.value = { left: parsed.left, top: parsed.top }
    }
  } catch (error) {
    chapterPosition.value = null
  }
}

function saveCollapseState() {
  try {
    localStorage.setItem(COLLAPSE_KEY, isCollapsed.value ? '1' : '0')
  } catch (error) {
    // Ignore storage errors.
  }
}

function loadCollapseState() {
  try {
    isCollapsed.value = localStorage.getItem(COLLAPSE_KEY) === '1'
  } catch (error) {
    isCollapsed.value = false
  }
}

function getPanelSize() {
  const width = chapterPanel.value?.offsetWidth || 216
  const height = chapterPanel.value?.offsetHeight || 300
  return { width, height }
}

function clampPosition(left, top) {
  const { width, height } = getPanelSize()
  const margin = 10
  const minLeft = margin
  const maxLeft = Math.max(minLeft, window.innerWidth - width - margin)
  const minTop = margin
  const maxTop = Math.max(minTop, window.innerHeight - height - margin)
  return {
    left: clamp(left, minLeft, maxLeft),
    top: clamp(top, minTop, maxTop)
  }
}

function ensureChapterPosition() {
  nextTick(() => {
    if (!showChapterNav.value) return
    const panel = chapterPanel.value
    if (!panel) return

    if (chapterPosition.value) {
      chapterPosition.value = clampPosition(
        chapterPosition.value.left,
        chapterPosition.value.top
      )
      return
    }

    const rect = panel.getBoundingClientRect()
    chapterPosition.value = clampPosition(rect.left, rect.top)
  })
}

function setWideScreen() {
  isWideScreen.value = window.matchMedia('(min-width: 1280px)').matches
  if (chapterPosition.value) {
    chapterPosition.value = clampPosition(
      chapterPosition.value.left,
      chapterPosition.value.top
    )
  }
}

function toggleCollapse() {
  isCollapsed.value = !isCollapsed.value
  saveCollapseState()
  ensureChapterPosition()
}

function stopDragging() {
  if (!isDragging.value) return
  isDragging.value = false
  window.removeEventListener('pointermove', handleDragMove)
  window.removeEventListener('pointerup', stopDragging)
  window.removeEventListener('pointercancel', stopDragging)
  saveChapterPosition()
}

function handleDragMove(event) {
  if (!isDragging.value) return
  chapterPosition.value = clampPosition(
    event.clientX - dragOffsetX,
    event.clientY - dragOffsetY
  )
}

function startDragging(event) {
  if (event.button !== 0) return
  ensureChapterPosition()

  const panel = chapterPanel.value
  if (!panel) return

  const rect = panel.getBoundingClientRect()
  const currentPosition = chapterPosition.value || { left: rect.left, top: rect.top }
  dragOffsetX = event.clientX - currentPosition.left
  dragOffsetY = event.clientY - currentPosition.top
  isDragging.value = true

  window.addEventListener('pointermove', handleDragMove)
  window.addEventListener('pointerup', stopDragging)
  window.addEventListener('pointercancel', stopDragging)
  event.preventDefault()
}

function collectHeadings() {
  const docRoot = document.querySelector('.VPDoc .vp-doc')
  if (!docRoot) {
    isDocPage.value = false
    navItems.value = []
    activeId.value = ''
    headingNodes = []
    return
  }

  isDocPage.value = true
  headingNodes = Array.from(docRoot.querySelectorAll('h2[id], h3[id]'))
  navItems.value = headingNodes.map((node) => ({
    id: node.id,
    level: node.tagName.toLowerCase(),
    text: shortText(node.textContent)
  }))
  activeId.value = navItems.value[0]?.id || ''
}

function paintActiveHeading() {
  if (!headingNodes.length) return
  headingNodes.forEach((node) => {
    node.classList.toggle('is-reading', node.id === activeId.value)
  })
}

function updateProgress() {
  const docRoot = document.querySelector('.VPDoc .vp-doc')
  if (!docRoot) {
    progress.value = 0
    return
  }

  const articleStart = docRoot.getBoundingClientRect().top + window.scrollY - 96
  const articleEnd = articleStart + docRoot.offsetHeight - window.innerHeight * 0.7

  if (articleEnd <= articleStart) {
    progress.value = 1
    return
  }

  const ratio = (window.scrollY - articleStart) / (articleEnd - articleStart)
  progress.value = clamp(ratio, 0, 1)
}

function updateActiveHeading() {
  if (!headingNodes.length) {
    activeId.value = ''
    return
  }

  const marker = window.scrollY + 140
  let current = headingNodes[0]
  for (const node of headingNodes) {
    if (node.offsetTop <= marker) {
      current = node
    } else {
      break
    }
  }

  activeId.value = current?.id || ''
}

function handleScrollOrResize() {
  if (rafId) return
  rafId = window.requestAnimationFrame(() => {
    updateProgress()
    updateActiveHeading()
    paintActiveHeading()
    showBackToTop.value = window.scrollY > 400
    rafId = 0
  })
}

function reinitializeForRoute() {
  nextTick(() => {
    collectHeadings()
    setWideScreen()
    ensureChapterPosition()
    handleScrollOrResize()
  })
}

onMounted(() => {
  loadChapterPosition()
  loadCollapseState()
  reinitializeForRoute()
  window.addEventListener('scroll', handleScrollOrResize, { passive: true })
  window.addEventListener('resize', handleScrollOrResize, { passive: true })
  window.addEventListener('resize', setWideScreen, { passive: true })
})

watch(
  () => route.path,
  () => {
    if (routeTimer) window.clearTimeout(routeTimer)
    routeTimer = window.setTimeout(reinitializeForRoute, 90)
  }
)

watch(showChapterNav, (visible) => {
  if (visible) ensureChapterPosition()
})

onBeforeUnmount(() => {
  if (routeTimer) window.clearTimeout(routeTimer)
  if (rafId) window.cancelAnimationFrame(rafId)
  stopDragging()
  window.removeEventListener('scroll', handleScrollOrResize)
  window.removeEventListener('resize', handleScrollOrResize)
  window.removeEventListener('resize', setWideScreen)
})
</script>

<template>
  <div v-if="showProgress" class="reading-progress" aria-hidden="true">
    <span class="reading-progress__bar" :style="{ transform: `scaleX(${progress})` }" />
  </div>

  <Transition name="back-to-top">
    <button
      v-if="showBackToTop && isDocPage"
      class="back-to-top-btn"
      aria-label="返回顶部"
      @click="scrollToTop()"
    >
      <svg class="back-to-top-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
        <path d="M12 19V5M5 12l7-7 7 7" />
      </svg>
    </button>
  </Transition>

  <aside
    v-if="showChapterNav"
    ref="chapterPanel"
    class="chapter-spotlight"
    :class="{ 'is-dragging': isDragging, 'is-collapsed': isCollapsed }"
    :style="chapterStyle"
    aria-label="章节导航"
  >
    <div class="chapter-spotlight__drag" @pointerdown="startDragging">
      <p class="chapter-spotlight__title">章节导航</p>
      <button
        class="chapter-spotlight__toggle"
        :class="{ 'is-collapsed': isCollapsed }"
        :aria-label="isCollapsed ? '展开章节导航' : '收起章节导航'"
        type="button"
        @pointerdown.stop
        @click.stop="toggleCollapse"
      />
    </div>
    <div v-show="!isCollapsed" class="chapter-spotlight__body">
      <a
        v-for="item in navItems"
        :key="item.id"
        class="chapter-spotlight__link"
        :class="[`is-${item.level}`, { 'is-active': item.id === activeId }]"
        :href="`#${item.id}`"
      >
        {{ item.text }}
      </a>
    </div>
  </aside>
</template>
